name: PR Preview & Deployment

on:
    pull_request:
        types: [opened, synchronize, reopened]
        branches: [main]

jobs:
    preview-build:
        name: Build PR Preview
        runs-on: ubuntu-latest

        steps:
            - name: Checkout PR code
              uses: actions/checkout@v4

            - name: Set up Python
              uses: actions/setup-python@v4
              with:
                  python-version: "3.11"
                  cache: "pip"

            - name: Install dependencies
              run: |
                  python -m pip install --upgrade pip
                  pip install -r requirements.txt

            - name: Run tests
              run: |
                  pytest test_app.py -v --cov=app --cov-report=term-missing

            - name: Test app can start
              run: |
                  timeout 30 streamlit run app.py --server.headless true --server.port 8501 &
                  sleep 10
                  curl -f http://localhost:8501 || exit 1
                  pkill -f streamlit

            - name: Comment on PR
              uses: actions/github-script@v7
              with:
                  script: |
                      const prNumber = context.payload.pull_request.number;
                      const message = `## 🚀 PR Preview Build Successful!

                      ✅ All tests passed
                      ✅ App successfully started
                      ✅ Dependencies installed correctly

                      ### 📊 Test Results
                      - 42 tests executed
                      - All tests passing
                      - Code coverage report generated

                      ### 🎯 Next Steps
                      1. Review the code changes
                      2. Test the new features locally
                      3. Approve and merge when ready

                      ### 🌐 To deploy to Streamlit Cloud:
                      After merging, your app will auto-deploy at:
                      \`https://alexandrahotti-data-stuff.streamlit.app\`

                      Or create a preview deployment by:
                      1. Go to [Streamlit Cloud](https://share.streamlit.io)
                      2. Add a new app from this PR branch
                      3. Set branch to: \`feature/ui-enhancements\`
                      `;

                      github.rest.issues.createComment({
                          owner: context.repo.owner,
                          repo: context.repo.repo,
                          issue_number: prNumber,
                          body: message
                      });

    code-quality:
        name: Code Quality Check
        runs-on: ubuntu-latest

        steps:
            - name: Checkout code
              uses: actions/checkout@v4

            - name: Set up Python
              uses: actions/setup-python@v4
              with:
                  python-version: "3.11"

            - name: Install linting tools
              run: |
                  python -m pip install --upgrade pip
                  pip install flake8 black isort

            - name: Check Python syntax
              run: |
                  python -m py_compile app.py test_app.py

            - name: Run flake8
              run: |
                  flake8 app.py test_app.py --count --select=E9,F63,F7,F82 --show-source --statistics
              continue-on-error: true

    test-matrix:
        name: Test on Python ${{ matrix.python-version }}
        runs-on: ubuntu-latest
        strategy:
            matrix:
                python-version: ["3.9", "3.10", "3.11"]

        steps:
            - name: Checkout code
              uses: actions/checkout@v4

            - name: Set up Python ${{ matrix.python-version }}
              uses: actions/setup-python@v4
              with:
                  python-version: ${{ matrix.python-version }}
                  cache: "pip"

            - name: Install dependencies
              run: |
                  python -m pip install --upgrade pip
                  pip install -r requirements.txt

            - name: Run tests
              run: |
                  pytest test_app.py -v --cov=app

            - name: Display Python version
              run: |
                  python --version
                  echo "✅ Tests passed on Python ${{ matrix.python-version }}"

    changes-summary:
        name: Generate Changes Summary
        runs-on: ubuntu-latest

        steps:
            - name: Checkout code
              uses: actions/checkout@v4
              with:
                  fetch-depth: 0

            - name: Get changed files
              id: changed-files
              run: |
                  echo "files<<EOF" >> $GITHUB_OUTPUT
                  git diff --name-only origin/main...HEAD >> $GITHUB_OUTPUT
                  echo "EOF" >> $GITHUB_OUTPUT

            - name: Count changes
              run: |
                  echo "### 📝 Changed Files" >> $GITHUB_STEP_SUMMARY
                  git diff --stat origin/main...HEAD >> $GITHUB_STEP_SUMMARY
                  echo "" >> $GITHUB_STEP_SUMMARY
                  echo "### ✨ Summary" >> $GITHUB_STEP_SUMMARY
                  echo "- Total files changed: $(git diff --name-only origin/main...HEAD | wc -l)" >> $GITHUB_STEP_SUMMARY
                  echo "- Lines added: $(git diff --numstat origin/main...HEAD | awk '{added+=$1} END {print added}')" >> $GITHUB_STEP_SUMMARY
                  echo "- Lines removed: $(git diff --numstat origin/main...HEAD | awk '{removed+=$2} END {print removed}')" >> $GITHUB_STEP_SUMMARY
