name: PR Preview Deploy (Fly.io)

on:
    pull_request:
        types: [opened, synchronize, reopened]

jobs:
    deploy-preview:
        runs-on: ubuntu-latest
        permissions:
            contents: read
            pull-requests: write

        steps:
            - name: Checkout code
              uses: actions/checkout@v4

            - name: Set app name
              id: app-name
              run: |
                  APP_NAME="data-stuff-pr-${{ github.event.number }}"
                  echo "app_name=$APP_NAME" >> $GITHUB_OUTPUT
                  echo "url=https://$APP_NAME.fly.dev" >> $GITHUB_OUTPUT

            - name: Setup Fly.io CLI
              uses: superfly/flyctl-actions/setup-flyctl@master

            - name: Deploy to Fly.io
              env:
                  FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
              run: |
                  # Create app if it doesn't exist
                  flyctl apps create ${{ steps.app-name.outputs.app_name }} --org personal || echo "App already exists"

                  # Deploy the app
                  flyctl deploy \
                    --app ${{ steps.app-name.outputs.app_name }} \
                    --remote-only \
                    --ha=false

            - name: Comment PR with preview URL
              uses: thollander/actions-comment-pull-request@v2
              with:
                  message: |
                      ## 🚀 Preview Deployment Ready!

                      Your preview environment is deployed and ready to view:

                      **🔗 Preview URL:** ${{ steps.app-name.outputs.url }}

                      This preview will be automatically updated on new commits and deleted when the PR is closed.
                  comment_tag: preview_url
